import { FontClasses, LanguagesClasses, ThemeClasses } from 'src/types';

export enum SearchParam {
  width = 'width',
  theme = 'theme',
  background = 'background',
  darkMode = 'darkMode',
  padding = 'padding',
  language = 'language',
  font = 'font',
  title = 'title',
  code = 'code',
}

export const THEME_CLASSES: ThemeClasses = {
  hyper: 'Hyper',
  oceanic: 'Oceanic',
  cottonCandy: 'Cotton Candy',
  gotham: 'Gotham',
  blueSteel: 'Blue Steel',
  hawaii: 'Hawaii',
  valentine: 'Valentine',
  witch: 'Witch',
  emerald: 'Emerald',
  blueFlame: 'Blue Flame',
};

export const THEME_VALUES = {
  hyper: 'bg-gradient-to-br from-pink-500 via-red-500 to-yellow-500',
  oceanic: 'bg-gradient-to-br from-green-300 via-blue-500 to-purple-600',
  cottonCandy: 'bg-gradient-to-br from-pink-300 via-purple-300 to-indigo-400',
  gotham: 'bg-gradient-to-br from-gray-700 via-gray-900 to-black',
  blueSteel: 'bg-gradient-to-br from-gray-400 via-gray-600 to-blue-800',
  hawaii: 'bg-gradient-to-br from-green-300 via-yellow-300 to-pink-300',
  valentine: 'bg-gradient-to-br from-red-200 to-red-600',
  witch: 'bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900',
  emerald: 'bg-gradient-to-br from-emerald-500 to-lime-600',
  blueFlame: 'bg-gradient-to-br from-amber-200 via-violet-600 to-sky-900',
};

export const LANGUAGE_CLASSES: LanguagesClasses = {
  bash: 'Bash',
  c: 'C',
  cpp: 'C++',
  csharp: 'C#',
  clojure: 'Clojure',
  crystal: 'Crystal',
  css: 'CSS',
  diff: 'Diff',
  dockerfile: 'Docker',
  elm: 'Elm',
  elixir: 'Elixir',
  erlang: 'Erlang',
  graphql: 'GraphQL',
  go: 'Go',
  haskell: 'Haskell',
  html: 'HTML',
  java: 'Java',
  javascript: 'JavaScript/JSX',
  json: 'JSON',
  kotlin: 'Kotlin',
  lisp: 'Lisp',
  lua: 'Lua',
  markdown: 'Markdown',
  matlab: 'MATLAB/Octave',
  pascal: 'Pascal',
  plaintext: 'Plaintext',
  powershell: 'Powershell',
  objectivec: 'Objective C',
  php: 'PHP',
  python: 'Python',
  ruby: 'Ruby',
  rust: 'Rust',
  scala: 'Scala',
  scss: 'SCS',
  sql: 'SQL',
  swift: 'Swift',
  toml: 'TOML',
  typescript: 'TypeScript/TSX',
  xml: 'XML',
  yaml: 'YAML',
};

export const FONT_CLASSES: FontClasses = {
  hack: 'Hack',
  consolas: 'Consolas',
  cascadiaCode: 'Cascadia Code',
  monoLisa: 'Mono Lisa',
};
